### ISSUE TITLE
Cannot build with Zig 0.14.1

### ISSUE THREAD

**Issue by Chirunos** [jiripospisil/drtl#1]
drtl f93ac5e59cfdfa25385da754fa8c5b107ef6fab7 (latest commit)
Zig 0.14.1/0.14.0 from [nixpkgs](https://search.nixos.org/packages?channel=25.05&show=zig&from=0&size=50&sort=relevance&type=packages&query=zig) (0.14.1 according to nixpkgs and 0.14.0 according to `zig version`) and 0.14.1 from Guix
Linux Mint MATE 22.1

`zig build` output (exit 2):
```
/home/user/drtl/build.zig:27:21: error: no field named 'host' in struct 'Build'
        .target = b.host,
                    ^~~~
/nix/store/dzdlr4lms4wgjvi02r1pcqh54iiq9pn5-zig-0.14.0/lib/zig/std/Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
referenced by:
    runBuild__anon_24691: /nix/store/dzdlr4lms4wgjvi02r1pcqh54iiq9pn5-zig-0.14.0/lib/zig/std/Build.zig:2428:44
    main: /nix/store/dzdlr4lms4wgjvi02r1pcqh54iiq9pn5-zig-0.14.0/lib/zig/compiler/build_runner.zig:339:29
    5 reference(s) hidden; use '-freference-trace=7' to see all references
```

Building it with Zig 0.13 from [nixpkgs](https://search.nixos.org/packages?channel=25.05&show=zig&from=0&size=50&sort=relevance&type=packages&query=zig) is successful.

**Comment by jiripospisil** [comment]
It should now build with 0.16. Sorry it took a while.

**Comment by Chirunos** [comment]
No worries! It works flawlessly now, thanks!
